//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.15 at 02:30:36 AM IST 
//


package com.armin.sap.ds.builder.api.models;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for HandlerTypes.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="HandlerTypes">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="div"/>
 *     &lt;enumeration value="sapui5"/>
 *     &lt;enumeration value="cvom"/>
 *     &lt;enumeration value="datasource"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "HandlerTypes")
@XmlEnum
public enum HandlerTypes implements Serializable {

    @XmlEnumValue("div")
    DIV("div"),
    @XmlEnumValue("sapui5")
    SAPUI_5("sapui5"),
    @XmlEnumValue("cvom")
    CVOM("cvom"),
    @XmlEnumValue("datasource")
    DATASOURCE("datasource");
    private final String value;

    HandlerTypes(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static HandlerTypes fromValue(String v) {
        for (HandlerTypes c: HandlerTypes.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
