//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.15 at 02:30:36 AM IST 
//


package com.armin.sap.ds.builder.models.domain;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * Specifies an extension component.
 * 
 * <p>Java class for Component complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Component">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.sap.com/bi/zen/sdk}Descriptable">
 *       &lt;sequence>
 *         &lt;element name="requireJs" type="{http://www.sap.com/bi/zen/sdk}RequireJSType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="stdInclude" type="{http://www.sap.com/bi/zen/sdk}StdInclude" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="jsInclude" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="cssInclude" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="property" type="{http://www.sap.com/bi/zen/sdk}Property" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="initialization" type="{http://www.sap.com/bi/zen/sdk}Initialization" minOccurs="0"/>
 *         &lt;element name="supportedBackend" type="{http://www.sap.com/bi/zen/sdk}BackendSystemType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="group" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="propertySheetPath" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="databound" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="newInstancePrefix" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="handlerType" type="{http://www.sap.com/bi/zen/sdk}HandlerTypes" default="div" />
 *       &lt;attribute name="icon" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="modes" type="{http://www.sap.com/bi/zen/sdk}UI5Modes" default="commons" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Component", propOrder = {
    "requireJs",
    "stdInclude",
    "jsInclude",
    "cssInclude",
    "property",
    "initialization",
    "supportedBackend"
})
public class Component
    extends Descriptable
{

    /**
	 * 
	 */
	private static final long serialVersionUID = -437063015265773945L;
	
	protected List<RequireJSType> requireJs;
    protected List<StdInclude> stdInclude;
    protected List<String> jsInclude;
    protected List<String> cssInclude;
    protected List<Property> property;
    protected Initialization initialization;
    @XmlSchemaType(name = "string")
    protected List<BackendSystemType> supportedBackend;
    @XmlAttribute(name = "group")
    protected String group;
    @XmlAttribute(name = "propertySheetPath")
    protected String propertySheetPath;
    @XmlAttribute(name = "databound")
    protected Boolean databound;
    @XmlAttribute(name = "newInstancePrefix")
    protected String newInstancePrefix;
    @XmlAttribute(name = "handlerType")
    protected HandlerTypes handlerType;
    @XmlAttribute(name = "icon")
    protected String icon;
    @XmlAttribute(name = "modes")
    protected List<UI5Mode> modes;

    /**
     * Gets the value of the requireJs property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the requireJs property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRequireJs().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RequireJSType }
     * 
     * 
     */
    public List<RequireJSType> getRequireJs() {
        if (requireJs == null) {
            requireJs = new ArrayList<RequireJSType>();
        }
        return this.requireJs;
    }

    /**
     * Gets the value of the stdInclude property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the stdInclude property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStdInclude().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link StdInclude }
     * 
     * 
     */
    public List<StdInclude> getStdInclude() {
        if (stdInclude == null) {
            stdInclude = new ArrayList<StdInclude>();
        }
        return this.stdInclude;
    }

    /**
     * Gets the value of the jsInclude property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the jsInclude property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getJsInclude().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getJsInclude() {
        if (jsInclude == null) {
            jsInclude = new ArrayList<String>();
        }
        return this.jsInclude;
    }

    /**
     * Gets the value of the cssInclude property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cssInclude property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCssInclude().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getCssInclude() {
        if (cssInclude == null) {
            cssInclude = new ArrayList<String>();
        }
        return this.cssInclude;
    }

    /**
     * Gets the value of the property property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the property property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProperty().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Property }
     * 
     * 
     */
    public List<Property> getProperty() {
        if (property == null) {
            property = new ArrayList<Property>();
        }
        return this.property;
    }

    /**
     * Gets the value of the initialization property.
     * 
     * @return
     *     possible object is
     *     {@link Initialization }
     *     
     */
    public Initialization getInitialization() {
        return initialization;
    }

    /**
     * Sets the value of the initialization property.
     * 
     * @param value
     *     allowed object is
     *     {@link Initialization }
     *     
     */
    public void setInitialization(Initialization value) {
        this.initialization = value;
    }

    /**
     * Gets the value of the supportedBackend property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the supportedBackend property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSupportedBackend().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BackendSystemType }
     * 
     * 
     */
    public List<BackendSystemType> getSupportedBackend() {
        if (supportedBackend == null) {
            supportedBackend = new ArrayList<BackendSystemType>();
        }
        return this.supportedBackend;
    }

    /**
     * Gets the value of the group property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGroup() {
        return group;
    }

    /**
     * Sets the value of the group property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGroup(String value) {
        this.group = value;
    }

    /**
     * Gets the value of the propertySheetPath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPropertySheetPath() {
        return propertySheetPath;
    }

    /**
     * Sets the value of the propertySheetPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPropertySheetPath(String value) {
        this.propertySheetPath = value;
    }

    /**
     * Gets the value of the databound property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isDatabound() {
        if (databound == null) {
            return false;
        } else {
            return databound;
        }
    }

    /**
     * Sets the value of the databound property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDatabound(Boolean value) {
        this.databound = value;
    }

    /**
     * Gets the value of the newInstancePrefix property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNewInstancePrefix() {
        return newInstancePrefix;
    }

    /**
     * Sets the value of the newInstancePrefix property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNewInstancePrefix(String value) {
        this.newInstancePrefix = value;
    }

    /**
     * Gets the value of the handlerType property.
     * 
     * @return
     *     possible object is
     *     {@link HandlerTypes }
     *     
     */
    public HandlerTypes getHandlerType() {
        if (handlerType == null) {
            return HandlerTypes.DIV;
        } else {
            return handlerType;
        }
    }

    /**
     * Sets the value of the handlerType property.
     * 
     * @param value
     *     allowed object is
     *     {@link HandlerTypes }
     *     
     */
    public void setHandlerType(HandlerTypes value) {
        this.handlerType = value;
    }

    /**
     * Gets the value of the icon property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIcon() {
        return icon;
    }

    /**
     * Sets the value of the icon property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIcon(String value) {
        this.icon = value;
    }

    /**
     * Gets the value of the modes property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the modes property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getModes().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link UI5Mode }
     * 
     * 
     */
    public List<UI5Mode> getModes() {
        if (modes == null) {
            modes = new ArrayList<UI5Mode>();
        }
        return this.modes;
    }

	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return String.format("id=%s, name=%s", id, name);
	}

    
}
