//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.15 at 02:30:36 AM IST 
//


package com.armin.sap.ds.builder.models.domain;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.armin.sap.ds.xml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _SdkExtension_QNAME = new QName("http://www.sap.com/bi/zen/sdk", "sdkExtension");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.armin.sap.ds.xml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Extension }
     * 
     */
    public Extension createExtension() {
        return new Extension();
    }

    /**
     * Create an instance of {@link Initialization }
     * 
     */
    public Initialization createInitialization() {
        return new Initialization();
    }

    /**
     * Create an instance of {@link Group }
     * 
     */
    public Group createGroup() {
        return new Group();
    }

    /**
     * Create an instance of {@link Descriptable }
     * 
     */
    public Descriptable createDescriptable() {
        return new Descriptable();
    }

    /**
     * Create an instance of {@link PropertyValue }
     * 
     */
    public PropertyValue createPropertyValue() {
        return new PropertyValue();
    }

    /**
     * Create an instance of {@link StdInclude }
     * 
     */
    public StdInclude createStdInclude() {
        return new StdInclude();
    }

    /**
     * Create an instance of {@link PossibleValueType }
     * 
     */
    public PossibleValueType createPossibleValueType() {
        return new PossibleValueType();
    }

    /**
     * Create an instance of {@link RequireJSType }
     * 
     */
    public RequireJSType createRequireJSType() {
        return new RequireJSType();
    }

    /**
     * Create an instance of {@link Option }
     * 
     */
    public Option createOption() {
        return new Option();
    }

    /**
     * Create an instance of {@link Component }
     * 
     */
    public ComponentExtended createComponent() {
        return new ComponentExtended();
    }

    /**
     * Create an instance of {@link Property }
     * 
     */
    public Property createProperty() {
        return new Property();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Extension }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.sap.com/bi/zen/sdk", name = "sdkExtension")
    public JAXBElement<Extension> createSdkExtension(Extension value) {
        return new JAXBElement<Extension>(_SdkExtension_QNAME, Extension.class, null, value);
    }

}
