//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.15 at 02:30:36 AM IST 
//


package com.armin.sap.ds.builder.models.domain;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PropertyType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="PropertyType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="String"/>
 *     &lt;enumeration value="Text"/>
 *     &lt;enumeration value="int"/>
 *     &lt;enumeration value="float"/>
 *     &lt;enumeration value="boolean"/>
 *     &lt;enumeration value="ScriptText"/>
 *     &lt;enumeration value="MultiLineText"/>
 *     &lt;enumeration value="Color"/>
 *     &lt;enumeration value="Url"/>
 *     &lt;enumeration value="ResultCell"/>
 *     &lt;enumeration value="ResultCellSet"/>
 *     &lt;enumeration value="ResultCellList"/>
 *     &lt;enumeration value="ResultSet"/>
 *     &lt;enumeration value="Object"/>
 *     &lt;enumeration value="Array"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "PropertyType")
@XmlEnum
public enum PropertyType implements Serializable {

    @XmlEnumValue("String")
    STRING("String"),
    @XmlEnumValue("Text")
    TEXT("Text"),
    @XmlEnumValue("int")
    INT("int"),
    @XmlEnumValue("float")
    FLOAT("float"),
    @XmlEnumValue("boolean")
    BOOLEAN("boolean"),
    @XmlEnumValue("ScriptText")
    SCRIPT_TEXT("ScriptText"),
    @XmlEnumValue("MultiLineText")
    MULTI_LINE_TEXT("MultiLineText"),
    @XmlEnumValue("Color")
    COLOR("Color"),
    @XmlEnumValue("Url")
    URL("Url"),
    @XmlEnumValue("ResultCell")
    RESULT_CELL("ResultCell"),
    @XmlEnumValue("ResultCellSet")
    RESULT_CELL_SET("ResultCellSet"),
    @XmlEnumValue("ResultCellList")
    RESULT_CELL_LIST("ResultCellList"),
    @XmlEnumValue("ResultSet")
    RESULT_SET("ResultSet"),
    @XmlEnumValue("Object")
    OBJECT("Object"),
    @XmlEnumValue("Array")
    ARRAY("Array");
    private final String value;

    PropertyType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PropertyType fromValue(String v) {
        for (PropertyType c: PropertyType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
