package com.armin.sap.ds.builder.navigator.tree;

public enum ProjectItemType {	
	GENERIC_FOLDER,
	RESOURCE_FOLDER,
	IMAGES_FOLDER,
	IMAGE,
	CSS_FOLDER,
	JS_FOLDER,
	META_INF_FOLDER,
	GENERIC_FILE,
	ADVANCED_PROPERTY_SHEET_FILE,
	BUILD_PROPERTIES_FILE,
	CASCADE_STYLE_SHEET_FILE,
	COMPONENT_FILE,
	EXTENSION_FILE,
	JAVASCRIPT_FILE,
	HTML_FILE,
	MANIFEST_FILE,
	PLUGIN_FILE,
	TARGET_FILE,
	PROJECT_PARENT,
	GROUP_NODE,
	UNKNOWN,
	EXTENSION_COLLECTION,
	COMPONENT_COLLECTION
}
