package com.armin.sap.ds.builder.navigator.tree;

public enum ProjectItemType {	
	GENERIC_FOLDER,
	RESOURCE_FOLDER,
	IMAGES_FOLDER,
	IMAGE,
	CSS_FOLDER,
	JS_FOLDER,
	META_INF_FOLDER,
	GENERIC_FILE,
	ADVANCED_PROPERTY_SHEET,
	BUILD_PROPERTIES,
	CASCADE_STYLE_SHEET,
	COMPONENT,
	EXTENSION,
	JAVASCRIPT,
	HTML,
	MANIFEST,
	PLUGIN,
	TARGET,
	WORKSPACE,
	GROUP,
	UNKNOWN,
	EXTENSION_COLLECTION,
	COMPONENT_COLLECTION
}
