//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.15 at 02:30:36 AM IST 
//


package com.armin.sap.ds.builder.project.models;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BackendSystemType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="BackendSystemType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="LOCAL"/>
 *     &lt;enumeration value="BIPLATFORM"/>
 *     &lt;enumeration value="NETWEAVER"/>
 *     &lt;enumeration value="HANA"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "BackendSystemType")
@XmlEnum
public enum BackendSystemType {

    LOCAL,
    BIPLATFORM,
    NETWEAVER,
    HANA;

    public String value() {
        return name();
    }

    public static BackendSystemType fromValue(String v) {
        return valueOf(v);
    }

}
