<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage
    xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore"
    name="extended"
    nsURI="www.armin.com/lumira_designer/models"
    nsPrefix="com.armin.sap.ds.builder.models.extended">
  <eClassifiers
      xsi:type="ecore:EClass"
      name="ComponentClient">
    <eOperations
        name="render"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="id"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        iD="true"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="init"
        eType="#//Method"
        containment="true"
        eKeys="#//Method/id"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="afterUpdate"
        eType="#//Method"
        containment="true"
        eKeys="#//Method/id"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="beforeUpdate"
        eType="#//Method"
        containment="true"
        eKeys="#//Method/id"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="sdkBaseClassType"
        eType="#//SDKBaseClassType"
        defaultValueLiteral="COMPONENT"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="data"
        unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Base64Binary"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="metadata"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Base64Binary"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="properties"
        upperBound="-1"
        eType="#//Property"
        containment="true"
        eKeys="#//Property/id"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="classMethods"
        upperBound="-1"
        eType="#//Method"
        containment="true"
        eKeys="#//Method/id"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="localMethods"
        upperBound="-1"
        eType="#//Method"
        containment="true"
        eKeys="#//Method/id"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="constructors"
        upperBound="-1"
        eType="#//Constructor"
        containment="true"
        eKeys="#//Constructor/id"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="localVariables"
        upperBound="-1"
        eType="#//Variable"
        containment="true"
        eKeys="#//Variable/id"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="constants"
        upperBound="-1"
        eType="#//Constant"
        containment="true"
        eKeys="#//Constant/id"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="comp"
        eType="#//JavaObject"
        transient="true"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EEnum"
      name="SDKBaseClassType">
    <eLiterals
        name="COMPONENT"/>
    <eLiterals
        name="DATA_SOURCE"
        value="1"/>
    <eLiterals
        name="DATA_BUFFER"
        value="2"/>
    <eLiterals
        name="UI5"
        value="3"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EDataType"
      name="JavaObject"
      instanceClassName="java.lang.Object"/>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="Constant">
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="id"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        iD="true"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="name"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="value"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="type"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="qualifier"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="isArray"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="Property">
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="id"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        iD="true"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="name"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="value"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="type"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="isReadOnly"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="getter"
        eType="#//Method"
        containment="true"
        eKeys="#//Method/id"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="setter"
        eType="#//Method"
        containment="true"
        eKeys="#//Method/id"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="Variable">
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="id"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        iD="true"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="name"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="value"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="type"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="Method">
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="id"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        iD="true"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="name"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="body"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="returnType"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="parameters"
        transient="true">
      <eGenericType
          eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EEList">
        <eTypeArguments
            eClassifier="#//Parameter"/>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="accessibiltyType"
        eType="#//AccessType"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EEnum"
      name="AccessType">
    <eLiterals
        name="PRIVATE"/>
    <eLiterals
        name="PUBLIC"
        value="1"/>
    <eLiterals
        name="PROTECTED"
        value="2"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="Parameter">
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="id"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        iD="true"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="name"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="value"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="type"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="Constructor">
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="id"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        iD="true"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="name"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="body"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="parameters"
        transient="true">
      <eGenericType
          eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EEList">
        <eTypeArguments
            eClassifier="#//Parameter"/>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="accessibiltyType"
        eType="#//AccessType"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="Section"
      abstract="true">
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="name"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="belongsToComponent"
        eType="#//JavaObject"
        transient="true"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="ConstantsSection"
      eSuperTypes="#//Section"/>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="LocalVariablesSection"
      eSuperTypes="#//Section"/>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="ConstructorsSection"
      eSuperTypes="#//Section"/>
</ecore:EPackage>
