package com.armin.sap.ds.support;

public interface ProjectConstants {

	String EXTENSION_TEMPLATE = "extension-template";
	String EULA = "eula";
	String VENDOR = "vendor";
	String VERSION = "version";
	String ID = "id";
	String ZTL_TEMPLATE = "ztl-template";
	String EXTENDS = "extends";
	String SUPER_CLASS_NAME = "superClassName";
	String NONE = "-- None --";
	String PACKAGE_NAME = "packageName";
	String DATE = "date";
	String AUTHOR = "author";
	String DESCRIPTION = "description";
	String COMPONENTS = "components";
	String COMPONENT_TEMPLATE = "component-template";
	String GROUP = "group";
	String DEFAULT = "Default";
	String PROPERTY_SHEET_PATH_ASSIGNMENT = "propertySheetPath=";
	String DOUBLE_QUOTES = "\"";
	String PROPERTY_SHEET_PATH_DEFAULT = "propertySheetPath=\"res/additional_properties_sheet/additional_properties_sheet.html\"";
	String PROPERTY_SHEET_PATH = "propertySheetPath";
	String TRUE = "databound=\"true\"";
	String DATABOUND = "databound";
	String COMMONS = "commons";
	String M = "m";
	String COMMONS_M = "commons m";
	String MODES = "modes";
	String HANDLER_TYPE = "handlerType";
	String ICON = "icon";
	String RES_IMAGES = "res/images/";
	String RES_IMAGES_COMPONENT_PNG = "res/images/component.png";
	String TOOLTIP = "tooltip";
	String TITLE = "title";
	String CLASS_NAME = "className";
	String EXTENSION_FILE_RELATIVE_PATH = "component.xml";
	String COMPONENT_CLOSE_TAG = "</component>";
	String COMPONENT_PLACEHOLDER = "\n ${components} \n";
	String COMPONENT_PATH = "res/js/";
	String COMPONENT_PATH_TEMPLATE = "componentPath";
	String REQUIRE_JS = "requireJs";
	String CSS_INCLUDE = "cssInclude";
	String PROPERTIES = "properties";
	String DEFAULT_VALUES = "defaultValues";
	String COMPONENT_CSS_PATH = "res/css/";
	String COMPONENT_CSS_PATH_TEMPLATE = "componentCssPath";
	String PROPERTY = "property";
	String VALUE = "value";
	String REQUIRE_JS_TEMPLATE = "require-js-template";
	String CSS_INCLUDE_TEMPLATE = "css-include-template";
	String DEFAULT_VALUE_TEMPLATE = "default-value-template";
	String HEIGHT = "HEIGHT";
	String WIDTH = "WIDTH";
	String NEW_LINE = "\n";
	String TECHNICAL_COMPONENT = "TECHNICAL_COMPONENT";
	String GROUP_TEMPLATE = "group-template";
	String GROUPS = "groups";
	String GROUP_CLOSE_TAG = "</group>";
	String DEFAULT_VALUE_CLOSE_TAG = "</defaultValue>";
}
