package com.armin.sap.ds.ext.navigator.elements;

public enum ProjectElementType {	
	GENERIC_FOLDER,
	RESOURCE_FOLDER,
	IMAGES_FOLDER,
	CSS_FOLDER,
	JS_FOLDER,
	META_INF_FOLDER,
	GENERIC_FILE,
	ADVANCED_PROPERTY_SHEET_FILE,
	BUILD_PROPERTIES_FILE,
	CASCADE_STYLE_SHEET_FILE,
	COMPONENT_FILE,
	EXTENSION_FILE,
	JAVASCRIPT_FILE,
	MANIFEST_FILE,
	PLUGIN_FILE,
	TARGET_FILE,
	PROJECT_PARENT,
	UNKNOWN
}
